services:
  boilerplate:
    image: ${CONTAINER_NAME}
    container_name: temp_${CONTAINER_NAME}
    platform: linux/amd64
    build:
      context: .
      target: final
    environment:
     - LEVEL 
    volumes:
      - ./testcases:/usr/src/app/testcases
      - ./src:/usr/src/app/src # UNCOMMENT THIS FOR LOCAL TESTING
      
      - ./output:/usr/src/app/output